wandb_version: 1

project_name:
  desc: null
  value: balanced_dataset
batch_size:
  desc: null
  value: 64
lr:
  desc: null
  value: 0.0005
epochs:
  desc: null
  value: 100
dropout:
  desc: null
  value: 0.5
weight_decay:
  desc: null
  value: 0.0005
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682472693.591043
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.8.16
      5: 0.14.2
      8:
      - 5
