wandb_version: 1

project_name:
  desc: null
  value: 1conv4linear
batch_size:
  desc: null
  value: 32
lr:
  desc: null
  value: 0.0005
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.6.13
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1681738228.588174
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.6.13
      5: 0.14.2
      8:
      - 1
      - 5
